### Задание 1
Создайте numpy array с элементами от числа N до 0
(например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).

In [1]:
import numpy as np

In [40]:
def N_to_0(N_f):
    task_1 = np.arange(N_f-1,-1,-1)
    return task_1

In [41]:
N = 10
N_to_0(N)

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

### Задание 2
Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

In [42]:
N = 10
task_2 = np.diag(N_to_0(N), k=0)

In [43]:
task_2

array([[9, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 8, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 7, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 6, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 5, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 4, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 3, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 2, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [21]:
sum(task_2.diagonal())

45

### Задание 3
Решите систему уравнений:

    4x + 2y + z = 4
    x + 3y = 12
    5y + 4z = -3

linalg.solve(a, b)

In [32]:
a = np.array( [ [4, 2, 1],[1, 3, 0],[0, 5, 4] ] )
b = np.array( [4, 12, -3] )

In [34]:
x = np.linalg.solve(a, b)
x

array([ 0.46666667,  3.84444444, -5.55555556])

In [36]:
np.allclose( np.dot(a, np.linalg.solve(a, b)), b )

True

### Задание 4
В материалах занятия раздел “Задача 4 домашнего задания”

Имеется матрица покупок в интернет-магазине. Столбец А - ID пользователя. Остальные столбцы - количество покупок категорий товаров этим пользователем:

In [2]:
users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
    np.int32
)

На сайт заходит очередной посетитель, о покупках которого известно следующее:

In [4]:
next_user_stats = np.array([0, 1, 2, 0, 0, 0])

Найдите самого похожего пользователя. Т. е. посчитайте косинусное сходство между этим пользователем и всеми пользователями из массива user_stats

In [37]:
def cosine( a, b ):
    """
    Подсчет косинуса угла между векторами a, b по их координатам
    """
    
    # длины векторов
    aLength = np.linalg.norm( a )
    bLength = np.linalg.norm( b )
    
    return np.dot( a, b ) / ( aLength * bLength )

In [38]:
users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
    np.int32
)

In [39]:
next_user_stats = np.array([0, 1, 2, 0, 0, 0])

i = 1
most_similar = cosine(next_user_stats, users_stats[0])

for i in range(users_stats.shape[0]):
    similar = cosine(next_user_stats, users_stats[i])
    if similar > most_similar:
        most_similar = similar
    i += 1
print(most_similar)

0.9486832980505138
